Improve initial instruction when opening the webpage
threema-ch/threema-web pull request #1124
Opened 2022-04-24 17:50 UTC by SimonHeimberg

Fixes #1112

Having icons for "menu" and "Settings" would be nice. But this is a good step.

2022-04-24 17:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/threema-ch/threema-web?pullRequest=1124) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/threema-ch/threema-web?pullRequest=1124) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/threema-ch/threema-web?pullRequest=1124) it.</sub>

2022-04-25 08:28 UTC, threema-danilo requested changes
This doesn't actually work yet, did you test it? Besides the stray colon sign in the attribute name, the information icon is very large, not centered, and a bit distracting.

![screenshot-20220425-102006](https://user-images.githubusercontent.com/78751145/165049619-89fba6b3-4eb1-4daa-8dd7-261d48fbbd13.png)

Maybe something like this would be better? (Font size is `.8em`)

2022-04-25 08:28 UTC, threema-danilo commented on src/partials/welcome.html
> +            <p class="instructions" translate-attr="{'title:': 'welcome.PLEASE_SCAN_INSTR'}">
Stray colon in the title attribute name.

2022-04-25 08:56 UTC, SimonHeimberg commented
> This doesn't actually work yet, did you test it? Besides the stray colon sign in the attribute name, the information icon is very large, not centered, and a bit distracting.
> 

Sorry, no, I did not test it. I do not have the setup to do it. I have forgotten to mention this. The only thing I tested was to put the icon in the code (in the debug tools of the browser).

> 
> Maybe something like this would be better? (Font size is `.8em`)
> 
> ![screenshot-20220425-102754](https://user-images.githubusercontent.com/78751145/165050775-b6ed6c4e-efe1-4c4d-93b2-fb8288d10dee.png)

I like your suggestion. It is short and clear. Will you implement it?

2022-04-26 10:20 UTC, threema-danilo commented
Replaced by #1126.

2022-04-26 10:20 UTC, closed without merging